services:

  web:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
    depends_on: 
      - db 
    environment: 
       - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres   
    networks: 
      - backend

  db:
    image: "postgres:16"     
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:    
