services:

  db:
    image: "postgres:16"     
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./db/migrations:/migrations
    networks: [backend]
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
        "up"
      ]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  web:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on: 
      db:
        condition: service_healthy
    env_file: 
      - .env
    networks: 
      - backend

  db_test:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
    networks: [backend]
    profiles: ["test"]

volumes:
  postgres_data:

networks:
  backend:    
