// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	SenderID  int64
	RecID     int64
	Body      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Password  []byte
	CreatedAt pgtype.Timestamptz
}
